### ISSUE TITLE
XML issues

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-8.0-TURKISH#35]
fix you XML issues
http://translators.xiaomi.eu/XML_MIUI7-Turkish-tr.html

**Comment by raoc999** [comment]
Hello Miroslav;
Turkish translation very confused. New people deleting and re-adding files
but didnt ask me or didnt look my files. I did ask anyone getting started.
I went correcting. Ridiculous to delete the file properly.

We always re-again starting. I fixed many files, but I saw I have many
errors again and again. Please just give authority me and Hakan. Also only
I and you will access device/hermes directory. Why? Because I do not want
the deterioration of the finished files. I hate this.  For example: I had a
very nice fix the Weather. Now it broke down again.There are many errors,
different weather in English, Turkish laguage was the same.

He deletes files properly. He never did not ask me. Now there are a lot of
mistakes. In this way, the project is not finished. Project no
leader.. Everyone
wants to get their name.  MUIU Turkey selling products  of Xiaomi. They
want to get their names. Miroslav please I want to translate only the Hermes
 files and give me the authority for device/hermes, not others. They
deleting my files, and insert wrong and etchnical translating ... You will
see many errors. Example: Sd Hc, IMEI, MMS, SMS etc ... Each
abbreviation should
be capitalized. In addition, I was constantly correcting errors. Now there
are a lot of mistakes. They do not fix it. I want to have a nice job. I'm
putting all Hermes files. I'll correct settings. I'll tell other files.
Please find the solution. This is the worst project. No such problems in
other languages.


Thanks your help. My leader is you. I do what you say... Thanks again.


Orhan

recep.ali.orhan.cakmak

2016-04-04 6:51 GMT+03:00 ingbrzy <notifications@github.com>:

**Comment by ingbrzy** [comment]
ok removed all except you and Hakan..

please do not add updated xmls into device/hermes directory only but also into main folder to be included in all supported device... you can move all to main... there are no many differences between devices so its safe...

**Comment by raoc999** [comment]
OK. I will do. I'm starting correction to Hakan's files. Soon to bit errors.

recep.ali.orhan.cakmak

2016-04-04 10:01 GMT+03:00 ingbrzy <notifications@github.com>:

**Comment by MIUITurkey** [comment]
Orhan hocam cep verir misin WhatsApp gurubu kuralım  bir tne
4 Nis 2016 ÖÖ 10:13 tarihinde "recep.ali.orhan.cakmak" <
notifications@github.com> yazdı:

**Comment by MIUITurkey** [comment]
Hello Miroslav;

I and my team (MIUI turkiye) hard working finish all translation. We fix it
issue after we finished all translation. I guess everything will be
finished until friday
4 Nis 2016 ÖÖ 10:39 tarihinde "Hasan ÖZKAN" <hasan.ozkan.35@gmail.com>
yazdı:

**Comment by ingbrzy** [comment]
ok great.. thank you..
